---
deployment:
  tasks:
    - source ../frontend-master.cfg
    - (cd frontend && npm install)
    - touch ./frontend/tmp/restart.txt
    - source ../backend-master.cfg
    - (cd backend && npm install)
    - touch ./backend/tmp/restart.txt

