name: Deploy to cPanel action

on: push

jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest
    env:
      CPANEL_DEPLOY_ROOT: ${{ secrets.CPANEL_FRONTEND_DEPLOY_ROOT }}
      CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
      CPANEL_USER: ${{ secrets.CPANEL_USER }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Set up SSH
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.CPANEL_OSAIWEBSITE_PRIVATE }}
      - run: ssh-keyscan $CPANEL_HOST >> $HOME/.ssh/known_hosts
      # Set up node
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      # Note: Shortcut way of restricting the branches that this runs on -- if a repo with the branch name exists, it will be pushed to.
      - run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          (cd frontend && npm install)
          npm run predeploy
          git add -f ./frontend/.next
          git commit -m "<ACTION_ONLY> Add production files to frontend for serving"
          # $(git rev-parse --abbrev-ref HEAD)
          git remote add cpanel "${CPANEL_USER}@${CPANEL_HOST}:${CPANEL_DEPLOY_ROOT}/master/"
          git push -f cpanel
