name: Deploy to cPanel action

on:
  push:
    branches:
      - master
      - staging
jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest
    env:
      CPANEL_DEPLOY_ROOT: ${{ secrets.CPANEL_FRONTEND_DEPLOY_ROOT }}
      CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
      CPANEL_USER: ${{ secrets.CPANEL_USER }}
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.CPANEL_OSAIWEBSITE_PRIVATE }}
      - run: ssh-keyscan $CPANEL_HOST >> $HOME/.ssh/known_hosts
      - run: |
          git remote add cpanel "${CPANEL_USER}@${CPANEL_HOST}:${CPANEL_DEPLOY_ROOT}/$(git rev-parse --abbrev-ref HEAD)/"
          git push -f cpanel
